### ISSUE TITLE
EntraOps module not working.

### ISSUE THREAD

**Issue by iahmed18** [Cloud-Architekt/EntraOps#17]
Trying to import EntraOps module but getting below error. Please support.

1- Downloaded EntraOps.psd1 & EntraOps.psm1
2- Run PowerShell module "PowerShell 7.4.2".
3-Getting Error:
PS C:\Users\Administrator\Documents\WindowsPowerShell\Modules\EntraOPS> **Import-Module ./EntraOps**
Install-EntraOpsAllRequiredModules: The term 'Install-EntraOpsAllRequiredModules' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Import-Module: The module to process 'EntraOps.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Users\Administrator\Documents\WindowsPowerShell\Modules\EntraOPS\EntraOps.psd1' was not processed because no valid module was found in any module directory.

**Comment by Cloud-Architekt** [comment]
@iahmed18 : Do you have download the EntraOps folder including all subfolder content (e.g., Public) and imported it in PowerShell Core?

**Comment by iahmed18** [comment]
![EntraOps](https://github.com/Cloud-Architekt/EntraOps/assets/162884193/299c89df-6e7a-465d-815d-4f8129b10369)
I think you are referring this folder.

**Comment by iahmed18** [comment]
Now its working Thanks for your support.
